### ISSUE TITLE
Could not connect to Omni sci in knn_model.py

### ISSUE THREAD

**Issue by jakerbrown** [cga-harvard/Data_Science_Big_Data_Projects#11]
When running the modified version of knn_model.py, I got the following error, related to connecting to OmniSci:

(omnisci) [jbrown613@holygpu2c0708 knn]$ python3 ~/sql/knn_model_merge.py
Connecting to Omnisci

Traceback (most recent call last):
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/pymapd/connection.py", line 312, in __init__
    self._session = self._client.connect(user, password, dbname)
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/omnisci/thrift/OmniSci.py", line 796, in connect
    return self.recv_connect()
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/omnisci/thrift/OmniSci.py", line 810, in recv_connect
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/thrift/protocol/TBinaryProtocol.py", line 148, in readMessageBegin
    name = self.trans.readAll(sz)
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/thrift/transport/TTransport.py", line 164, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/thrift/transport/TSocket.py", line 143, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/n/home09/jbrown613/sql/knn_model_merge.py", line 20, in <module>
    conn=connect(user="admin", password="HyperInteractive", host="localhost", port=8670, dbname="omnisci") #use your port number
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/pymapd/connection.py", line 130, in connect
    idpsslverify=idpsslverify,
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/pymapd/connection.py", line 317, in __init__
    f"Connection failed with port {port} and "
ValueError: Connection failed with port 8670 and protocol 'binary'. Try port 6274 for protocol == binary or 6273, 6278 or 443 for http[s]

**Comment by dkakkar** [comment]
You might not be connecting to the right port! Please connect ti the backend port in your script not the frontend. Refer here under "Running scripts" section for instructions on how to find backend port: https://github.com/cga-harvard/GIS_Apps_on_HPC/blob/master/Using%20FASRC%20Geospatial%20Resources.pdf

**Comment by jakerbrown** [comment]
Should I not have changed the port numbers already in the script with my requested job’s port?

**Comment by dkakkar** [comment]
Yes, you should change the port to your job port but you are not providing the correct post from your job. Did you get the port number from output.log file as mentioned in the pdf?
