### ISSUE TITLE
Troubleshooting knn_model.py script

### ISSUE THREAD

**Issue by jakerbrown** [cga-harvard/Data_Science_Big_Data_Projects#12]
While running the modified knn_model.py script I got the following error. It appears to be related to converting the merged table to omnisci, but I do not know what the error message "Cannot convert pyarrow.lib.ChunkedArray to pyarrow.lib.Array" means or how to fix it:

(omnisci) [jbrown613@holygpu2c0705 neighbors]$ time python3 ~/sql/knn_model_merge.py
Connecting to Omnisci
Connected Connection(omnisci://admin:***@localhost:9893/omnisci?protocol=binary)
Traceback (most recent call last):
  File "/n/home09/jbrown613/sql/knn_model_merge.py", line 37, in <module>
    conn.load_table("m",m,create='infer',method='arrow')
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/pymapd/connection.py", line 687, in load_table
    return self.load_table_arrow(table_name, data)
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/pymapd/connection.py", line 835, in load_table_arrow
    data, metadata, preserve_index=preserve_index
  File "/n/home09/jbrown613/.conda/envs/omnisci/lib/python3.6/site-packages/pymapd/_pandas_loaders.py", line 248, in _serialize_arrow_payload
    data = pa.RecordBatch.from_pandas(data_, preserve_index=preserve_index)
  File "pyarrow/table.pxi", line 704, in pyarrow.lib.RecordBatch.from_pandas
  File "pyarrow/table.pxi", line 749, in pyarrow.lib.RecordBatch.from_arrays
TypeError: Cannot convert pyarrow.lib.ChunkedArray to pyarrow.lib.Array

real    5m54.114s
user    5m11.406s
sys     0m25.939s

**Comment by jakerbrown** [comment]
An addendum to this:

I tried to look on Immerse, to see if the parts of the script that loaded data into OmniSci worked, and after running the script I cannot connect to Immerse through the local host, it times out. This same issue happened yesterday when I ran this as well.
